config/routes.rb
Rails.application.routes.draw do


  #mount Spree::Core::Engine, :at => '/mall'
  get 'lifestyles/index'
  get 'lifestyles/new'
  get 'lifestyles/create'
  get 'lifestyles/update'
  get 'lifestyle/index'
  get 'lifestyle/new'
  get 'lifestyle/create'
  get 'lifestyle/update'
  get 'coming_soon/index'
  get 'albums/new'
  get 'albums/all_albums'
  get 'albums/edit'
  get 'albums/create'
  get 'albums/update'
  get 'albums/delete'
  get 'stores/index'
  get 'stores/new'
  get 'stores/show'
  get 'stores/create'
  get 'stores/update'
  get 'stores/activate'
  get 'stores/deactivate'
  get 'music/index'
  get 'gallery/index'
  get "/callback" => "facebook#callback"
  get "/facebook_profile" => "facebook#facebook_profile"
  get 'visitors/news'
  get 'visitors/gallery'
  get 'visitors/videos'
  get 'visitors/social'
  get 'visitors/events'
  get 'visitors/contact'
  get 'videos/test'
  get 'visitors/stage'
  get 'visitors/show_gallery'
  

  resources :feature_banners
  devise_for :users
  devise_for :admins
  resources :lifestyles
  resources :albums
  resources :users
  resources :stores
  resources :tracks
  resources :main_banners
  resources :galleries
  resources :images
  resources :features
  resources :videos
  resources :artists
  resources :events
  resources :international_features
  resources :local_features
  #resources :vip_tickets
  #resources :standard_tickets
  
  
  # get '/auth/:provider/callback', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy', as: :logout

  match '/gallery' => 'visitors#gallery', :via => :get
  match '/gallery/:id' => 'galleries#show_gallery', :via => :get
  match '/music' => 'tracks#music', :via => :get
  match '/news' => 'features#index', :via => :get
  match '/social' => 'visitors#social', :via => :get
  match '/videos' => 'videos#index', :via => :get
  match '/contact_us' => 'visitors#contact', :via => :get
  match '/artist' => 'artists#show', :via => :get
  match '/store' => 'visitors#store', :via => :get
  match '/new_artist_upload' => 'artists#new', :via => :get
  #match '/new_feature_upload' => 'features#new', :via => :get
  match '/new_local_feature_upload' => 'local_features#new', :via => :get
  match '/local_features_index' => 'local_features#admin_index', :via => :get
  match '/new_international_feature_upload' => 'international_features#new', :via => :get
  match '/international_features_index' => 'international_features#admin_index', :via => :get
  match '/downloads' => 'artists#downloads', :via => :get
  match '/new_music_upload' => 'tracks#new', :via => :get
  match '/new_gallery_upload' => 'galleries#new', :via => :get
  match '/admin_show' => 'galleries#admin_show', :via => :get
  match '/new_video_upload' => 'videos#new', :via => :get
  match '/all_videos' => 'videos#all_videos', :via => :get 
  match '/new_store_upload' => 'stores#new', :via => :get
  match '/new_event_upload' => 'events#new', :via => :get
  match '/portfolio' => 'visitors#portfolio', :via => :get
  match '/new_banner_upload' => 'main_banners#new', :via => :get
  match '/admin_index' => 'features#admin_index', :via => :get
  match '/artist_songs' => 'artists#artist', :via => :get
  match '/banners_index' => 'main_banners#index', :via => :get
  match '/users' => 'users#index', :via => :get
  match '/stage' => 'visitors#stage', :via => :get
  match '/coming_soon' => 'coming_soon#index', :via => :get
  match '/team' => 'visitors#team', :via => :get
  match '/new_sports_upload' => 'lifestyles#new', :via => :get
  match '/sports_admin_index' => 'lifestyles#lifestyle_admin_index', :via => :get
  match '/sports' => 'lifestyles#index', :via => :get
  match '/admin_album_index' => 'albums#admin_album_index', :via => :get
  match '/admin_show_album' => 'albums#admin_show_album', :via => :get
  match '/admin_all_music' => 'tracks#admin_all_music', :via => :get
  match '/admin_artist_index' => 'artists#admin_artist_index', :via => :get
  match '/new_album_upload' => 'albums#new', :via => :get
  match '/lifestyle_admin_index' => 'lifestyles#lifestyle_admin_index', :via => :get
  match '/admin' => 'admins#index', :via => :get
  match '/admin_all_events' => 'events#admin_all_events', :via => :get
  match '/admin_show_album/:id' => 'albums#admin_show_album', :via => :get
  match '/mall' => 'spree/home#index', :via => :get
  #root to: 'coming_soon#index'
  root :to => "visitors#index"
end

app/models/feature_banner.rb
class FeatureBanner < ActiveRecord::Base
end

app/controllers/feature_banners_controller.rb
class FeatureBannersController < ApplicationController
  before_action :set_feature_banner, only: [:show, :edit, :update, :destroy]

  # GET /feature_banners
  # GET /feature_banners.json
  def index
    @feature_banners = FeatureBanner.all
  end

  # GET /feature_banners/1
  # GET /feature_banners/1.json
  def show
  end

  # GET /feature_banners/new
  def new
    @feature_banner = FeatureBanner.new
  end

  # GET /feature_banners/1/edit
  def edit
  end

  # POST /feature_banners
  # POST /feature_banners.json
  def create
    @feature_banner = FeatureBanner.new(feature_banner_params)

    respond_to do |format|
      if @feature_banner.save
        format.html { redirect_to @feature_banner, notice: 'Feature banner was successfully created.' }
        format.json { render :show, status: :created, location: @feature_banner }
      else
        format.html { render :new }
        format.json { render json: @feature_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feature_banners/1
  # PATCH/PUT /feature_banners/1.json
  def update
    respond_to do |format|
      if @feature_banner.update(feature_banner_params)
        format.html { redirect_to @feature_banner, notice: 'Feature banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature_banner }
      else
        format.html { render :edit }
        format.json { render json: @feature_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feature_banners/1
  # DELETE /feature_banners/1.json
  def destroy
    @feature_banner.destroy
    respond_to do |format|
      format.html { redirect_to feature_banners_url, notice: 'Feature banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature_banner
      @feature_banner = FeatureBanner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_banner_params
      params.require(:feature_banner).permit(:name, :description, :image, :link)
    end
end

app/views/feature_banners/_form.html.haml
= form_for @feature_banner do |f|
  - if @feature_banner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feature_banner.errors.count, "error")} prohibited this feature_banner from being saved:"
      %ul
        - @feature_banner.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :link
    = f.text_field :link
  .actions
    = f.submit 'Save'

app/views/feature_banners/edit.html.haml
%h1 Editing feature_banner

= render 'form'

= link_to 'Show', @feature_banner
\|
= link_to 'Back', feature_banners_path

app/views/feature_banners/index.html.haml
%h1 Listing feature_banners

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Image
      %th Link
      %th
      %th
      %th

  %tbody
    - @feature_banners.each do |feature_banner|
      %tr
        %td= feature_banner.name
        %td= feature_banner.description
        %td= feature_banner.image
        %td= feature_banner.link
        %td= link_to 'Show', feature_banner
        %td= link_to 'Edit', edit_feature_banner_path(feature_banner)
        %td= link_to 'Destroy', feature_banner, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feature banner', new_feature_banner_path

app/views/feature_banners/new.html.haml
%h1 New feature_banner

= render 'form'

= link_to 'Back', feature_banners_path

app/views/feature_banners/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @feature_banner.name
%p
  %b Description:
  = @feature_banner.description
%p
  %b Image:
  = @feature_banner.image
%p
  %b Link:
  = @feature_banner.link

= link_to 'Edit', edit_feature_banner_path(@feature_banner)
\|
= link_to 'Back', feature_banners_path