config/routes.rb
Rails.application.routes.draw do


  #mount Spree::Core::Engine, :at => '/mall'
  get 'lifestyles/index'
  get 'lifestyles/new'
  get 'lifestyles/create'
  get 'lifestyles/update'
  get 'lifestyle/index'
  get 'lifestyle/new'
  get 'lifestyle/create'
  get 'lifestyle/update'
  get 'coming_soon/index'
  get 'albums/new'
  get 'albums/all_albums'
  get 'albums/edit'
  get 'albums/create'
  get 'albums/update'
  get 'albums/delete'
  get 'stores/index'
  get 'stores/new'
  get 'stores/show'
  get 'stores/create'
  get 'stores/update'
  get 'stores/activate'
  get 'stores/deactivate'
  get 'music/index'
  get 'gallery/index'
  get "/callback" => "facebook#callback"
  get "/facebook_profile" => "facebook#facebook_profile"
  get 'visitors/news'
  get 'visitors/gallery'
  get 'visitors/videos'
  get 'visitors/social'
  get 'visitors/events'
  get 'visitors/contact'
  get 'videos/test'
  get 'visitors/stage'
  get 'visitors/show_gallery'
  

  resources :feature_banners
  devise_for :users
  devise_for :admins
  resources :lifestyles
  resources :albums
  resources :users
  resources :stores
  resources :tracks
  resources :main_banners
  resources :galleries
  resources :images
  resources :features
  resources :videos
  resources :artists
  resources :events
  resources :international_features
  resources :local_features
  #resources :vip_tickets
  #resources :standard_tickets
  
  
  # get '/auth/:provider/callback', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy', as: :logout

  match '/gallery' => 'visitors#gallery', :via => :get
  match '/gallery/:id' => 'galleries#show_gallery', :via => :get
  match '/music' => 'tracks#music', :via => :get
  match '/news' => 'features#index', :via => :get
  match '/social' => 'visitors#social', :via => :get
  match '/videos' => 'videos#index', :via => :get
  match '/contact_us' => 'visitors#contact', :via => :get
  match '/artist' => 'artists#show', :via => :get
  match '/store' => 'visitors#store', :via => :get
  match '/new_artist_upload' => 'artists#new', :via => :get
  #match '/new_feature_upload' => 'features#new', :via => :get
  match '/new_local_feature_upload' => 'local_features#new', :via => :get
  match '/local_features_index' => 'local_features#admin_index', :via => :get
  match '/new_international_feature_upload' => 'international_features#new', :via => :get
  match '/international_features_index' => 'international_features#admin_index', :via => :get
  match '/downloads' => 'artists#downloads', :via => :get
  match '/new_music_upload' => 'tracks#new', :via => :get
  match '/new_gallery_upload' => 'galleries#new', :via => :get
  match '/admin_show' => 'galleries#admin_show', :via => :get
  match '/new_video_upload' => 'videos#new', :via => :get
  match '/all_videos' => 'videos#all_videos', :via => :get 
  match '/new_store_upload' => 'stores#new', :via => :get
  match '/new_event_upload' => 'events#new', :via => :get
  match '/portfolio' => 'visitors#portfolio', :via => :get
  match '/new_banner_upload' => 'main_banners#new', :via => :get
  match '/admin_index' => 'features#admin_index', :via => :get
  match '/artist_songs' => 'artists#artist', :via => :get
  match '/banners_index' => 'main_banners#index', :via => :get
  match '/users' => 'users#index', :via => :get
  match '/stage' => 'visitors#stage', :via => :get
  match '/coming_soon' => 'coming_soon#index', :via => :get
  match '/team' => 'visitors#team', :via => :get
  match '/new_sports_upload' => 'lifestyles#new', :via => :get
  match '/sports_admin_index' => 'lifestyles#lifestyle_admin_index', :via => :get
  match '/sports' => 'lifestyles#index', :via => :get
  match '/admin_album_index' => 'albums#admin_album_index', :via => :get
  match '/admin_show_album' => 'albums#admin_show_album', :via => :get
  match '/admin_all_music' => 'tracks#admin_all_music', :via => :get
  match '/admin_artist_index' => 'artists#admin_artist_index', :via => :get
  match '/new_album_upload' => 'albums#new', :via => :get
  match '/lifestyle_admin_index' => 'lifestyles#lifestyle_admin_index', :via => :get
  match '/admin' => 'admins#index', :via => :get
  match '/admin_all_events' => 'events#admin_all_events', :via => :get
  match '/admin_show_album/:id' => 'albums#admin_show_album', :via => :get
  match '/mall' => 'spree/home#index', :via => :get
  #root to: 'coming_soon#index'
  root :to => "visitors#index"
end

app/models/video.rb
class Video < ActiveRecord::Base
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  
  validates :link, presence: true, format: YT_LINK_FORMAT
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  layout "admin", only: [:new, :create, :update, :all_videos]

  def index
    @videos = Video.order('created_at DESC')
  end

  def all_videos
    @videos = Video.order('created_at DESC')
  end

  def test
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:success] = 'Video deleted!'
    redirect_to '/all_videos'
  end

  def edit
    @video = Video.find(params[:id])
  end

  def show
    @video = Video.find(params[:id])
  end
  
  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to '/all_videos'
    else
      render :new
    end
  end


  private

  def video_params
    params.require(:video).permit(:link,:category)
  end
end

app/views/videos/all_videos.html.haml
%script{:src => "/scripts/masonry.pkgd.min.js", :type => "text/javascript"}
%script{:src => "/scripts/isotope.pkgd.min.js", :type => "text/javascript"}
%script{:src => "/scripts/isotope.init.js", :type => "text/javascript"}
#services
  .container
    .row
      .row.services
        .col-sm-12
          .row
            %h1 All Videos
            %p= link_to "New Video", new_video_path
            .grid
              -for video in @videos
                .grid-item.grid-sizer.col-sm-4.servicebox.featured_club
                  .servicebox-image
                    %a.vid-item.pretty-photo{"data-gal" => "prettyPhoto[gallery-photo-thumb]", :href => "https://www.youtube.com/watch?v=#{video.uid}"}
                      %img{:alt => "#{video.title}", :src => "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg"}
                  .servicebox-inner
                    %p
                      #{video.title}
                  .servicebox-inner
                    %p
                      = link_to "edit", edit_video_path(video) | 
                      = button_to 'delete', video, confirm: 'Are you sure?', method: :delete

app/views/videos/edit.html.haml
#services
  .container
    .row
.container
  %h1 New video
  = form_for @video do |f|
    = render 'shared/errors', object: @video
    .form-group
      = f.label :link, :class => "control-label col-sm-2"
      .col-sm-10
        = f.text_field :link, class: 'form-control', required: true
        %span.help-block A link to the video on YouTube.
    .form-group
      = f.label :category, :class => "control-label col-sm-2"
      .col-sm-10 
        = f.submit class: 'btn btn-primary'

app/views/videos/index.html.haml
%script{:src => "/scripts/masonry.pkgd.min.js", :type => "text/javascript"}
%script{:src => "/scripts/isotope.pkgd.min.js", :type => "text/javascript"}
%script{:src => "/scripts/isotope.init.js", :type => "text/javascript"}

.container
  .row.module.parallax.parallax-profiles
    .col-md-12
      %h1.wow.fadeInUp{"data-wow-duration" => "1s"} Redvillage TV
    .row
      #player.col-sm-9
        :javascript
          // 2. This code loads the IFrame Player API code asynchronously.
          var tag = document.createElement('script');

          tag.src = "https://www.youtube.com/iframe_api";
          var firstScriptTag = document.getElementsByTagName('script')[0];
          firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

          // 3. This function creates an <iframe> (and YouTube player)
          //    after the API code downloads.
          var player;
          function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
              height: '520',
              width: '100%',
              videoId: 'foQusxK9iT8',
              events: {
                'onReady': onPlayerReady,
              }
            });
          }

          // 4. The API will call this function when the video player is ready.
          function onPlayerReady(event) {
            <!-- event.target.getPlayList(); -->
          }

          // 5. The API calls this function when the player's state changes.
          //    The function indicates that when playing a video (state=1),
          //    the player should play for six seconds and then stop.
          var done = false;
          function onPlayerStateChange(event) {
            if (event.data == YT.PlayerState.PLAYING && !done) {
              setTimeout(stopVideo, 6000);
              done = true;
            }
          }
          function stopVideo() {
            player.stopVideo();
          }
          function playVideo(videoId) {          
            player.loadVideoById(videoId, 0, "medium");
          }
      .col-md-3
        #video_carousel.flexslider
          %ul.slides
            -for video in @videos
              %li
                .vid-item
                  .thumb
                    %a{:href => "#{video.link}", :onclick => "playVideo('#{video.uid}')"}
                      %img{:src => "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg"}
                      .desc
                        #{video.title}
:javascript
  $(document).ready(function(){
    $('#video_carousel').flexslider({
      animation: "slide",
      direction: "vertical",
      controlNav: false,
      animationLoop: false,
      slideshow: false,
      itemWidth: 380,
      itemMargin: 1,
      asNavFor: '#slider'
    });
 
  })

app/views/videos/new.html.haml
#services
  .container
    .row
.container
  %h1 New video
  = form_for @video do |f|
    = render 'shared/errors', object: @video
    .form-group
      = f.label :link, :class => "control-label col-sm-2"
      .col-sm-10
        = f.text_field :link, class: 'form-control', required: true
        %span.help-block A link to the video on YouTube.
    .form-group
      = f.label :category, :class => "control-label col-sm-2"
      .col-sm-10 
        = f.submit class: 'btn btn-primary'

app/views/videos/show.html.haml
#services
  .container
    .row
.container
  %h1 New video
  = form_for @video do |f|
    = render 'shared/errors', object: @video
    .form-group
      = f.label :link, :class => "control-label col-sm-2"
      .col-sm-10
        = f.text_field :link, class: 'form-control', required: true
        %span.help-block A link to the video on YouTube.
    .form-group
      = f.label :category, :class => "control-label col-sm-2"
      .col-sm-10 
        = f.submit class: 'btn btn-primary'

app/views/videos/test.html.haml
#services
  .container
    .row
/ start gallery
#gallery.text-center
  .container
    .row.text-center
      .tabs.tabs-style-linebox.wow.fadeInUp{"data-wow-duration" => "2s"}
        %nav
          %ul.filters
            %li.hvr-sweep-to-top.active.filter{"data-filter" => "all"}
              %span All
            %li.hvr-sweep-to-top.filter{"data-filter" => ".girlsPub"}
              %span Girls Pub
            %li.hvr-sweep-to-top.filter{"data-filter" => ".danceParty"}
              %span Dance Party
            %li.hvr-sweep-to-top.filter{"data-filter" => ".videos"}
              %span Videos
  .container-fluid
    .row.gallery.text-center
      .col-md-12.noPadding
        .gallery-photo-grid
          .gallery-photos
            .gallery-photos-thumb

              - if @videos.any?
                - @videos.in_groups_of(3) do |group|
                  - group.take(5).collect do |video|
                    .gallery-photo-item.mix.danceParty.wow.fadeIn
                      %a.pretty-photo{"data-gal" => "prettyPhoto[gallery-photo-thumb]", :href => "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg"}
                        .photo-thumb
                          %img{:alt => "image-1", :src => "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg"}
                        .overlay
                          %span.gallery-icon
                            %i.fa.fa-search-plus.fa-2x
                          